export { default as Home } from "./Home"
export { default as Courses } from "./Courses"
export { default as Resources } from "./Resources"
export { default as MyProfile } from "./MyProfile"
export { default as Messeges } from "./Messeges"
export { default as Comunity } from "./Comunity"
export { default as CourseDetails } from "./CourseDetails"
export { default as CourseCreate } from "./CourseCreate"