export { default as Home } from "./Home"
export { default as Courses } from "./Courses"
export { default as Resources } from "./Resources"
export { default as Settings } from "./Settings"
export { default as Messeges } from "./Messeges"